### ISSUE TITLE
magpie 2.0 : hadoop 3.0 w/ no-local-dir

### ISSUE THREAD

**Issue by chu11** [LLNL/magpie#264]
Missing some subtlety.  After running, container syslog contains

```
2017-12-22 15:28:51,407 WARN [main] org.eclipse.jetty.webapp.WebAppContext: Failed startup of context o.e.j.w.WebAppContext@1a0b5323{/\
,null,null}{/mapreduce}
java.lang.IllegalStateException: Parent for temp dir not configured correctly: writeable=false
        at org.eclipse.jetty.webapp.WebInfConfiguration.makeTempDirectory(WebInfConfiguration.java:340)
        at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:308)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:485)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:521)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1070)
        at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:408)
        at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:397)
        at org.apache.hadoop.mapreduce.v2.app.client.MRClientService.serviceStart(MRClientService.java:147)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceStart(MRAppMaster.java:1287)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$6.run(MRAppMaster.java:1738)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1962)
        at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1734)
        at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1668)
```

Underneath this is a

```
org.apache.hadoop.yarn.webapp.WebAppException: Error starting http server
```

then a bunch of NULL pointer exception.

Assumption is that somehow the map tasks have the wrong HADOOP_CONF_DIR

**Comment by chu11** [comment]
container "launch_container.sh" indeed has the wrong HADOOP_CONF_DIR.  How does it get the HADOOP_CONF_DIR of the master node and not the local one?

**Comment by chu11** [comment]
I also tried adding HADOOP_CONF_DIR to the mapred site file

```
<property>
  <name>yarn.app.mapreduce.am.env</name>
  <value>HADOOP_MAPRED_HOME=HADOOPHOME,HADOOP_CONF_DIR=HADOOPCONFDIR</value>
  <description>User added environment variables for the MR App Master
  processes. Example :
  1) A=foo  This will set the env variable A to foo
  2) B=$B:c This is inherit tasktracker's B env variable.
  </description>
</property>

<property>
  <name>mapred.child.env</name>
  <value>HADOOP_MAPRED_HOME=HADOOPHOME,HADOOP_CONF_DIR=HADOOPCONFDIR</value>
  <description>User added environment variables for the task processes.
  Example :
  1) A=foo  This will set the env variable A to foo
  2) B=$B:c This is inherit nodemanager's B env variable on Unix.
  3) B=%B%;c This is inherit nodemanager's B env variable on Windows.
  </description>
</property>
```

But this didn't seem to work as well.

**Comment by chu11** [comment]
issue w/ launch container appears to be solved, some logic errors in my original no-local-dir patch.  But still not working.

**Comment by chu11** [comment]
issue with in my tests, now fixed
